import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ReactPlayer from "react-player";
import { useState, useEffect } from "react";
import { imageLoader } from "../next.config";

export default function Home() {
  const [video, setVideo] = useState<any>(null);
  useEffect(() => {
    setVideo(<ReactPlayer url="http://d150qtgzj6fhnq.cloudfront.net/zahid_sample_video_szu.mp4" controls={true} />);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{video}</main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image loader={imageLoader} src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
